### ISSUE TITLE
Create Game using Js

### ISSUE THREAD

**Issue by Manikanta05** [Manikanta05/Hacktoberfest#18]
Create a game using js

Note: Create a file with appropriate name in WEB folder if you know to write internal js.
or
Create a folder with appropriate name and add your files there.

**Comment by aritrasen12345** [comment]
I want to work on it. Can u assign it to me?

**Comment by ANIK-DATTA** [comment]
I want to work on it too. Assign me please.

**Comment by ANIK-DATTA** [comment]
I have made pr request please check and merge
thank you

**Comment by yas-sisodia** [comment]
@Manikanta05 can you please assign this task to me

**Comment by devilraj98** [comment]
can you assign the task to me

**Comment by devilraj98** [comment]
i just create a pr in your repo of dice game please accept it for hactoberfest
