### ISSUE TITLE
Create Notes Taking application

### ISSUE THREAD

**Issue by Manikanta05** [Manikanta05/Hacktoberfest#3]
Create a web based notes taking application with simple ui design, with features like

- Add task
- Edit task
- Delete task

**Comment by Valenception** [comment]
Hi! can I implement that?

**Comment by Manikanta05** [comment]
> Hi! can I implement that?

Yeah you can @Valenception

**Comment by MayankHora** [comment]
Hi, I can fix this. Can you assign me this issue?

**Comment by Dcode-k** [comment]
@Manikanta05 can I work on this issue?

**Comment by Manikanta05** [comment]
> @Manikanta05 can I work on this issue?

@Dcode-k You can start working on it!

**Comment by Dcode-k** [comment]
thanks

**Comment by yas-sisodia** [comment]
@Manikanta05 can you please assign this task to me ?

**Comment by Manikanta05** [comment]
> @Manikanta05 can you please assign this task to me ?

You can submit pull request directly!
