### ISSUE TITLE
Create a Password Generator 

### ISSUE THREAD

**Issue by Manikanta05** [Manikanta05/Hacktoberfest#8]
Create a Password Generator with user inputs like 

- length
- include special symbols or not
- include numbers or not

_Note: Add your file named as **PasswordGenerator.html** in WEB folder._

**Comment by jvgalvao14** [comment]
Hey! Can I work on this?

**Comment by Manikanta05** [comment]
> Hey! Can I work on this?

Yeah sure!

**Comment by MayankHora** [comment]
Hi, I can fix this. Can you assign me this issue?

**Comment by Manikanta05** [comment]
> Hi, I can fix this. Can you assign me this issue?

@MayankHora Sure
