### ISSUE TITLE
Create LinkedList Visualizer 

### ISSUE THREAD

**Issue by Manikanta05** [Manikanta05/Hacktoberfest#9]
Create a application to visualize
- addition of node
- modification of node
- deletion of node

_Note : Add your files in Folder named **LinkedListVisualizer**_

**Comment by Diganta-Dutta2020** [comment]
Hey @Manikanta05  can you assign me this one ?

**Comment by Manikanta05** [comment]
> Hey @Manikanta05 can you assign me this one ?

@Diganta-Dutta2020 you can work on it!
